from app.models.role import Role
from app.models.usuario import Usuario
from app.models.curso import Curso
from app.models.turma import Turma
from app.models.aluno import Aluno
from app.models.turma_disciplina import TurmaDisciplina
from app.models.aluno_disciplina_extra import AlunoDisciplinaExtra
from app.models.sessao_aula import SessaoAula
from app.models.presenca import PresencaAluno
